### ISSUE TITLE
Error handling for incorrect header units

### ISSUE THREAD

**Issue by greenberger** [Ehlmann-research-group/WISER#26]
If the wavelength units don't match the list in the software, the image won't open. See file (emailed) 220309h1450. Wavelength units are µm, and WISER is unhappy. Preferred behavior would be to open with wavelength units unknown.

Traceback in error: 
Traceback (most recent call last):
  File "wiser\gui\app.py", line 506, in show_open_file_dialog
  File "wiser\gui\app_state.py", line 255, in open_file
  File "wiser\raster\loader.py", line 57, in load_from_file
  File "wiser\raster\dataset.py", line 97, in __init__
  File "wiser\raster\dataset_impl.py", line 606, in read_band_unit
  File "wiser\raster\utils.py", line 51, in get_spectral_unit
KeyError: b'\xb5m'

![image](https://user-images.githubusercontent.com/46727915/172265825-b082381c-73b5-41d4-bfc2-375e60840db7.png)

**Comment by Joooshe** [comment]
Not yet done. Personally, I like the option for a dialog box saying something like "Incomplete Metadata" with the option to fill out more metadata or skip. Also I think it would be good to open the image without wavelengths and not error because then the user will notice that their image doesn't have wavelengths which points them in the direction of how to fix it (if they know to go into the header file to change it).
