### ISSUE TITLE
Single band grayscale images not showing up in grayscale

### ISSUE THREAD

**Issue by greenberger** [Ehlmann-research-group/WISER#83]
Single band image not showing up in grayscale despite saying it is?

![image](https://github.com/user-attachments/assets/36d7e9d9-9458-46df-abf4-cc589ebcb5b6)

Also, colormaps are all some blue-black bar? This is what it shows me for the orange colormap:
![image](https://github.com/user-attachments/assets/eabee392-7670-4f01-9f60-efa0b255c693)

wiser\gui\rasterview.py:52: RuntimeWarning: invalid value encountered in cast
{'apiKey': '29bf39226c3071461f3d0630c9ced4b6',
 'events': [{'app': {'type': None, 'version': '1.1a11'},
             'breadcrumbs': [],
             'context': None,
             'device': {'hostname': 'LAPTOP-HDO795H8',
                        'runtimeVersions': {'python': '3.11.9'}},
             'exceptions': [{'errorClass': 'IndexError',
                             'message': 'list index out of range',
                             'stacktrace': [{'code': {},
                                             'file': 'wiser\\gui\\rasterview.py',
                                             'inProject': True,
                                             'lineNumber': 538,
                                             'method': 'update_display_image'},
                                            {'code': {},
                                             'file': 'wiser\\gui\\rasterview.py',
                                             'inProject': True,
                                             'lineNumber': 500,
                                             'method': 'set_display_bands'},
                                            {'code': {},
                                             'file': 'wiser\\gui\\rasterpane.py',
                                             'inProject': True,
                                             'lineNumber': 1004,
                                             'method': 'set_display_bands'},
                                            {'code': {},
                                             'file': 'wiser\\gui\\app.py',
                                             'inProject': True,
                                             'lineNumber': 889,
                                             'method': '_on_display_bands_change'}],
                             'type': 'python'}],
             'featureFlags': [],
             'groupingHash': None,
             'libRoot': 'C:\\Users\\rgree\\Downloads\\ZipWISERPlanet1x3\\WISER\\_internal\\Lib\\site-packages',
             'metaData': {'extraData': {}, 'request': {}, 'session': {}},
             'projectRoot': 'C:\\Users\\rgree\\Downloads\\ZipWISERPlanet1x3\\WISER',
             'releaseStage': 'production',
             'session': None,
             'severity': 'error',
             'severityReason': {'type': 'unhandledException'},
             'unhandled': True,
             'user': {}}],
 'notifier': {'name': 'Python Bugsnag Notifier',
              'url': 'https://github.com/bugsnag/bugsnag-python',
              'version': '4.7.1'},
 'payloadVersion': '4.0'}
Traceback (most recent call last):
  File "wiser\gui\app.py", line 889, in _on_display_bands_change
  File "wiser\gui\rasterpane.py", line 1004, in set_display_bands
  File "wiser\gui\rasterview.py", line 500, in set_display_bands
  File "wiser\gui\rasterview.py", line 538, in update_display_image
IndexError: list index out of range

**Comment by Joooshe** [comment]
Was fixed in the release around Jan 30, 2025.
